// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCYL3GMXILpliDE3r8uW3nOTQJTwI85yE',
    appId: '1:126312877369:android:676b310a90cbfb94456ce8',
    messagingSenderId: '126312877369',
    projectId: 'dating-ee43e',
    databaseURL: 'https://dating-ee43e-default-rtdb.firebaseio.com',
    storageBucket: 'dating-ee43e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYuRRs8itow8QftBcz2a_-D2wwowUaTCk',
    appId: '1:126312877369:ios:db112c90785132f6456ce8',
    messagingSenderId: '126312877369',
    projectId: 'dating-ee43e',
    databaseURL: 'https://dating-ee43e-default-rtdb.firebaseio.com',
    storageBucket: 'dating-ee43e.appspot.com',
    androidClientId: '126312877369-09lqhaonl8iotm2iccsnr18gmqva75hm.apps.googleusercontent.com',
    iosClientId: '126312877369-08vrrcoh1ipq0lnng66ij0o3f53np0u8.apps.googleusercontent.com',
    iosBundleId: 'com.tiff.tiffinbox',
  );
}
